### ISSUE TITLE
Wrong handling newlines in output of text columns

### ISSUE THREAD

**Issue by nostrilia** [cmoog/vscode-sql-notebook#2]
Hello, thanks for this extension, it looks very promising.

There is a bug: If text column in MySQL database contains line breaks, the output of this column is wrongly divided to several rows:
![image](https://user-images.githubusercontent.com/47560932/130066893-58aca713-e5ea-4fb5-967d-f0bd2f89497e.png)

Expected output:

![image](https://user-images.githubusercontent.com/47560932/130066942-9eb61126-034c-4020-a4aa-21d0d7b657ed.png)

**Comment by cmoog** [comment]
Yikes! Thanks for reporting this. I'll have a fix included in the next release.

**Comment by nostrilia** [comment]
Almost there :-)
![image](https://user-images.githubusercontent.com/47560932/130196647-c0579d81-50a6-41e1-a8bf-4d84360c24da.png)

**Comment by cmoog** [comment]
Dang. Ok this should do the trick: https://github.com/cmoog/vscode-sql-notebook/commit/4db1e0555c0f51b5b348bc047818f99beab9e2fc
