### ISSUE TITLE
Each row of output rendering with separate labels and scrolling

### ISSUE THREAD

**Issue by AJTonyKane** [cmoog/vscode-sql-notebook#31]
Hi Charlie.

I just installed, began using, and really love this extension.  Thanks so much for the initiative in making and sharing it.  The only thing is I am experiencing a curiosity that you may have insights on: my cell output presentation (with my Windows install) is very different from what appears in the (Mac) screen shots on its marketplace flash page.   In my case, each output row (apparently up to 500 based on experimentation) is rendered independently, with its own header row and horizontal scrolling. 

Is this normal for the Windows version?  If not, what Extension or setting should I be looking into that might be causing?  I tried disabling a few, quitting & restarting VS Code, but had no luck.  This was based on my noticing that one of the "More Actions" available from that output cell's ellipsis icon is "Change Presentation", but when I click that, there is only one option to select:

text/markdown _currently active_
Markdown it renderer (vscode.markdown-language-features)

Still really cool, but thanks in advance for any suggestions or advice on getting SELECT output to look more like those screen shot.  

Regards and best wishes,  
Tony

![image](https://user-images.githubusercontent.com/19287204/160221711-6105671e-ca42-4b85-9b4f-b131eac1143b.png)

**Comment by cmoog** [comment]
Thank you for the detail in this bug report. I've been able to reproduce this issue on all platforms, so this was likely a regression introduced in `v0.4.0`. @AJTonyKane can you confirm that you are using the `mysql` driver?

If so, I'll be releasing a patch with the fix shortly.

**Comment by cmoog** [comment]
I've verified that this issue is fixed in version [0.5.1](https://github.com/cmoog/vscode-sql-notebook/releases/tag/v0.5.1). Thanks again for the detailed bug report.

I'll be prioritizing the creation of proper tests so that driver specific regressions like this can't happen again.

**Comment by AJTonyKane** [comment]
Wow!  Thanks so much.  After I submitted, I was mostly off-line over the weekend, and am sorry I didn't see your request, so I could confirm I was using MySQL.   Terrific to see the revision, and all the more reason to evangelize your great work.  All the best, T
