### ISSUE TITLE
Add MSSQL Support

### ISSUE THREAD

**Issue by gengle** [cmoog/vscode-sql-notebook#4]
Reviewing database abstractions in place, it should be fairly easy to integrate with MSSQL server.  I'm not a typescript expect but if there is something I can help with let me know.

**Comment by cmoog** [comment]
I published version `0.1.1` with MSSQL driver support. @gengle, can you verify it works as expected?

**Comment by nicholasmivation** [comment]
@cmoog, is there a way to connect to a sqlserver that doesn't have a port and uses azure ad for auth?

**Comment by cmoog** [comment]
@nicholasmivation Currently this won't work, but since we're using the [node-mssql](https://github.com/tediousjs/node-mssql) driver, we _could_ add support for this functionality by adding some additional form fields to the connection configuration menu.

I've opened a new issue for tracking.
