### ISSUE TITLE
UX confusion on how to configure PostgreSQL connection

### ISSUE THREAD

**Issue by Danilo-Carajiliascov** [cmoog/vscode-sql-notebook#43]
when I run a query I recive this messege:
No active connection found. Configure database connections in the SQL Notebook sidepanel.

**Comment by cmoog** [comment]
Is the side panel interface displaying properly? If so, please use the provided form to create new PostgreSQL connections. The following screenshot shows an example of how this should look:

![](https://user-images.githubusercontent.com/7585078/147782853-c0ea8ecb-e5f7-410f-83c2-af3d0562302e.png)

**Comment by Danilo-Carajiliascov** [comment]
> Is the side panel interface displaying properly? If so, please use the provided form to create new PostgreSQL connections. The following screenshot shows an example of how this should look:
> 
> ![](https://user-images.githubusercontent.com/7585078/147782853-c0ea8ecb-e5f7-410f-83c2-af3d0562302e.png)

Thanks, cmoog !!
I didn't configure the side panel properly.

It's working now !
