### ISSUE TITLE
Support for SSH connection

### ISSUE THREAD

**Issue by renodesper** [cmoog/vscode-sql-notebook#57]
Some databases are protected with a bastion server. So, I think it will be beneficial for us to add the capability to connect to the database through an SSH connection.

**Comment by cmoog** [comment]
I think the cleaner solution here is for the user to run a TCP port forwarding session. Then they can connect through localhost. Otherwise, we'll need to handle SSH configuration, potentially with secret values, which comes with a plethora of edge cases.
