### ISSUE TITLE
Is there a way to check/manually edit/export a stored DB config ?

### ISSUE THREAD

**Issue by yw662** [cmoog/vscode-sql-notebook#65]
DB configured with sql-notebook is not stored in the user settings file, and the UI provides only creation and deletion. What if a user wants to manually edit a configured DB if it is hard to find where it is physically stored ?

**Comment by cmoog** [comment]
At present, it is not possible to modify connection configurations through the UI. I agree this is sometimes desirable and would be a useful feature.
