### ISSUE TITLE
open to 2 different connection simultaneously

### ISSUE THREAD

**Issue by wonb168** [cmoog/vscode-sql-notebook#69]

**Comment by cmoog** [comment]
This capability is not yet supported.

**Comment by cmoog** [comment]
It isn't obvious to be how this could work in a way that is simple and clear to the user. Specifically, how are connections mapped to open SQL files? I want to configuration overload and connecting to multiple databases in a single vscode workspace does not feel like a common use case to me.

Until a feasible design is proposed, I'm going to close with as `not planned`.
