### ISSUE TITLE
File conversion problem sql->jupyter

### ISSUE THREAD

**Issue by SmallHdcc** [cmoog/vscode-sql-notebook#79]
When I wrote a jupyter file, I wrote a lot of cells, but when I re-use the sql notebook to open, it actually became only one cell, I feel very broken, because this is my work for a long time, if it can not run, I will face punishment, please be sure to solve quickly, thank you!

**Comment by cmoog** [comment]
Please reference the FAQ, found [here](https://github.com/cmoog/vscode-sql-notebook#faq), for understanding why this is happening. If you still encounter issues, please reopen this issue with more context and steps for reproducing them.

**Comment by SmallHdcc** [comment]
I found my problem, it is due to the format of the newline, because I used the CRLF format of the newline, resulting in all the content is identified as a cell, in VScode change to LF, can solve the problem, thank u
