### ISSUE TITLE
Publish on Open VSX

### ISSUE THREAD

**Issue by Fabrizio-Volonte** [cmoog/vscode-sql-notebook#8]
This extension works great, but I'm using VSCodium so I'm unable to use the VSCode Marketplace and I have to download the `.vsix` file everytime.
Could you please publish this extension on the [Open VSX Registry](https://open-vsx.org/about) so installation and updating becomes easier for users of all OSS builds of VSCode?

**Comment by cmoog** [comment]
Sorry for the delay. Yes, I'll have this published on Open VSX soon and will automate this publish step for future releases.

**Comment by cmoog** [comment]
Closing this out since the latest version is now live of the open-vsx registry. I opened an issue to start the namespace verification process.

https://open-vsx.org/extension/cmoog/sqlnotebook
https://github.com/EclipseFdn/open-vsx.org/issues/783
