### ISSUE TITLE
ERROR: Query read timeout, code max execution time only 30 seconds?

### ISSUE THREAD

**Issue by dbcoffee** [cmoog/vscode-sql-notebook#86]
When I execute a piece of SQL code, I receive an error message "Query read timeout". The code execution time is shown as 30 seconds. However, when I run this piece of code in other software, there are no issues. How can I resolve this?

**Comment by cmoog** [comment]
Please provide specific steps to reproduce the issue.

**Comment by cmoog** [comment]
Closing until reproduction steps are posted.
