### ISSUE TITLE
The output is limited to 25 lines, can I change this?

### ISSUE THREAD

**Issue by fvlnl** [cmoog/vscode-sql-notebook#87]
I see only 25 lines of output and then .... Can I change the number of output lines?

![image](https://github.com/cmoog/vscode-sql-notebook/assets/20888705/4bc3bd34-c130-444c-98dd-83c95a159b4c)

**Comment by cmoog** [comment]
Yes, this is configurable via the vscode settings option `SQLNotebook.maxResultRows`. 

Reference: https://github.com/cmoog/vscode-sql-notebook/blob/87b95ae1e20c118606b4c3e5e45d682677f90865/package.json#L111
